
server:
  port: ${APP_PORT:8070}
  servlet:
    context-path: /episen/api/v1
    
management:
  health:
    show-details: always
  metrics:
    enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics
    
security:
  require-ssl: false
  basic:
    enabled: false